apiVersion: v1
kind: Pod
metadata:
  name: asyncdigitransit
spec:
  containers:
  - name: ingester-container
    image: INSERT_YOUR_INGESTER_IMAGE_LOCATION_HERE
    env:
      - name: ROLLBAR_TOKEN
        value: INSERT_YOUR_ROLLBAR_TOKEN_HERE
      - name: SOURCE_CONFIG
        valueFrom:
          configMapKeyRef:
            name: configs
            key: sampledigitransitconfig.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
  namespace: default
data:
  sampledigitransitconfig.json: |
    {
      "namespace": "bus",
      "type": "asyncapimqtt",
      "source": "sample_digitransit_spec.yml",
      "options": {
        "ably_options": {
          "production": {
            "key": "INSERT_YOUR_API_KEY_HERE"
          }
        }
      }
    }
